# Generated by Django 4.0.5 on 2022-06-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('dni', models.IntegerField()),
                ('nacimiento', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('obra_soc', models.CharField(max_length=150)),
                ('localidad', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion', models.CharField(max_length=150)),
            ],
        ),
    ]
