# Generated by Django 4.0.5 on 2022-06-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.IntegerField(unique=True),
        ),
    ]
