# Generated by Django 4.0.5 on 2022-06-28 23:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes_app', '0002_alter_paciente_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(5000), django.core.validators.MaxValueValidator(99999999)]),
        ),
    ]
